apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: django-backend-deploy
  name: backend
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django-backend-deploy
status:
  loadBalancer: {}